### ISSUE TITLE
Message read/unread status

### ISSUE THREAD

**Issue by mrusme** [mrusme/superhighway84#22]
As mentioned [here](https://github.com/mrusme/superhighway84/issues/11#issuecomment-1002271724) it would be great if there was a way to see which messages were read already.

The easiest solution would be to simply store that information somewhere on the local disk.

**Comment by derricw** [comment]
Conventional location is probably `$XDG_DATA_HOME` and if unset, `~/.local/share/superhighway84`

**Comment by mrusme** [comment]
This has now been implemented in master as a basic color change in title.

**Comment by apatheticposture** [comment]
I noticed your change.  A thing to consider is maybe the color should only change if I hit enter on an article and open it, or otherwise mark it manually.  The issue is that if I want to key down and skip a few articles, but maybe read them later, by keying down over them it marks them as read.

Another possibility is what Outlook does, which is it only tags a mail as read if focus is on it for a specific length of time; usually a few seconds.

**Comment by mrusme** [comment]
@apatheticposture the timed mark as read makes sense, implemented that one.
