### ISSUE TITLE
../../go/pkg/mod/github.com/ipfs/go-ipfs@v0.9.1/plugin/loader/load_unix.go:8:2: package plugin is not in GOROOT (/usr/src/plugin)

### ISSUE THREAD

**Issue by dbasinge** [mrusme/superhighway84#5]
```
╰─ go build .              
../../go/pkg/mod/github.com/ipfs/go-ipfs@v0.9.1/plugin/loader/load_unix.go:8:2: package plugin is not in GOROOT (/usr/src/plugin)
```

Getting the following error when building.

**Comment by mrusme** [comment]
What go version are you using? Not exactly sure where this comes from tbh, the paths seem strange as well.

**Comment by dbasinge** [comment]
Using Fedora 35, with gcc-go and ipfs version 0.10.0

**Comment by krionical** [comment]
Same here with arch linux: ./go/pkg/mod/github.com/ipfs/go-ipfs@v0.9.1/plugin/loader/load_unix.go:8:2: package plugin is not in GOROOT (/usr/src/plugin)

**Comment by mrusme** [comment]
I ran a quick search and found other projects where people have similar issues, e.g. https://github.com/golangci/golangci-lint/issues/1465 - however, I'm not quite sure how to fix this issue as I didn't stumble upon it so far.

Are you able to compile/install other Go projects in general? (E.g. IPFS itself) If that's not the case it might be an issue with your specific installation of Go or with the configuration of your GOPATH or maybe even GOROOT.

**Comment by krionical** [comment]
> Are you able to compile/install other Go projects in general? (E.g. IPFS itself) If that's not the case it might be an issue with your specific installation of Go or with the configuration of your GOPATH or maybe even GOROOT.

Yes. As far as I know, this issue has only happened with this particular piece of software.

**Comment by mrusme** [comment]
I've continued investigating into this issue and here's what I found that other people suggested:

- [set `go env -w GO111MODULE=off`](https://stackoverflow.com/questions/61845013/package-xxx-is-not-in-goroot-when-building-a-go-project)
- [do the opposite and set some more env vars](https://stackoverflow.com/questions/64448560/golang-package-is-not-in-goroot-usr-local-go-src-packagename)
- [do the opposite again and set GOPATH](https://stackoverflow.com/questions/68693154/package-is-not-in-goroot)
- [use `auto` instead of `on` or `off`](https://stackoverflow.com/questions/65572966/error-package-is-not-in-goroot-when-go-run)

I believe that this might however be an issue with the specific installations, hence I can't really help much here. On my machine, as well as on some VPS that I've used, as well as on GitHub's CI it seems to be working just fine.

Maybe try using the [official installation](https://go.dev/doc/install) and see if that works for you?
